# Generated by Django 5.0.1 on 2024-03-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetailsmodel',
            name='store_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='storedetailsmodel',
            name='store_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
