# Generated by Django 5.0.1 on 2024-05-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('StoreApp', '0001_initial'),
        ('VehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_created_at', models.DateTimeField(auto_created=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_image', models.ImageField(null=True, upload_to='User/')),
                ('user_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('user_address', models.CharField(max_length=500)),
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.districtmodel')),
                ('user_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.statemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
            options={
                'db_table': 'UserAddress_table',
            },
        ),
        migrations.CreateModel(
            name='UserBookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.servicemodel')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.storedetailsmodel')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.useraddressmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
            options={
                'db_table': 'user_booking_table',
            },
        ),
        migrations.CreateModel(
            name='UserReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.CharField(max_length=10)),
                ('user_review_points', models.IntegerField()),
                ('image_upload', models.ImageField(upload_to='Store')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userbookingmodel')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.storedetailsmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
            options={
                'db_table': 'user_review_table',
            },
        ),
    ]
