# Generated by Django 5.0.1 on 2024-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_useraddressmodel_user_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodel',
            name='user_address',
            field=models.CharField(max_length=500),
        ),
    ]
