# Generated by Django 5.0.1 on 2024-05-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryModel',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_category_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'service_Category_Table',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=1000, null=True)),
                ('service_price', models.CharField(max_length=100, null=True)),
                ('service_image', models.ImageField(upload_to='Store')),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.servicecategorymodel')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.storedetailsmodel')),
            ],
            options={
                'db_table': 'Service_Table',
            },
        ),
        migrations.CreateModel(
            name='VehicleAccessoryModel',
            fields=[
                ('vehicle_accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_accessory_name', models.CharField(max_length=1000, null=True)),
                ('vehicle_accessory_type', models.CharField(max_length=1000, null=True)),
                ('vehicle_accessory_category', models.CharField(max_length=1000, null=True)),
                ('vehicle_accessory_description', models.CharField(max_length=1000, null=True)),
                ('vehicle_accessory_price', models.CharField(max_length=100, null=True)),
                ('vehicle_accessory_image', models.ImageField(upload_to='VehicleAccessories')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.storedetailsmodel')),
            ],
            options={
                'db_table': 'vehicle_accessory_table',
            },
        ),
        migrations.CreateModel(
            name='AccessoryImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessory_image', models.ImageField(upload_to='VehicleAccessory')),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehicleaccessorymodel')),
            ],
            options={
                'db_table': 'Accessory_Images_Table',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_brand', models.CharField(max_length=1000, null=True)),
                ('vehicle_model', models.CharField(max_length=1000, null=True)),
                ('vehicle_year', models.CharField(max_length=4, null=True)),
                ('vehicle_fuel_type', models.CharField(max_length=1000, null=True)),
                ('vehicle_color', models.CharField(max_length=1000, null=True)),
                ('vehicle_variant', models.CharField(max_length=1000, null=True)),
                ('vehicle_budget', models.CharField(max_length=1000, null=True)),
                ('vehicle_body_type', models.CharField(max_length=1000, null=True)),
                ('vehicle_transmission', models.CharField(max_length=1000, null=True)),
                ('vehicle_seating_capacity', models.CharField(max_length=10)),
                ('vehicle_image', models.ImageField(upload_to='Vehicle')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.category')),
            ],
            options={
                'db_table': 'Vehicle_table',
            },
        ),
        migrations.CreateModel(
            name='VehicleImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='Vehicle')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehiclemodel')),
            ],
            options={
                'db_table': 'Vehicle_Images_Table',
            },
        ),
        migrations.AddField(
            model_name='vehicleaccessorymodel',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='BrandImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_image', models.ImageField(upload_to='Vehicle')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehiclemodel')),
            ],
            options={
                'db_table': 'Brand_Images_Table',
            },
        ),
        migrations.CreateModel(
            name='VehiclePartsModel',
            fields=[
                ('vehicle_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_part_name', models.CharField(max_length=1000, null=True)),
                ('vehicle_part_type', models.CharField(max_length=1000, null=True)),
                ('vehicle_part_description', models.CharField(max_length=1000, null=True)),
                ('vehicle_part_category', models.CharField(max_length=1000, null=True)),
                ('vehicle_part_price', models.CharField(max_length=100, null=True)),
                ('vehicle_part_image', models.ImageField(upload_to='VehicleParts')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.storedetailsmodel')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehiclemodel')),
            ],
            options={
                'db_table': 'vehicle_parts_table',
            },
        ),
        migrations.CreateModel(
            name='PartsImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('parts_image', models.ImageField(upload_to='VehicleParts')),
                ('parts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehiclepartsmodel')),
            ],
        ),
    ]
