# Generated by Django 5.0.1 on 2024-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
