# Generated by Django 5.0.1 on 2024-03-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleApp', '0002_alter_vehiclemodel_vehicle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessory_image', models.ImageField(upload_to='VehicleAccessory')),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehicleaccessorymodel')),
            ],
            options={
                'db_table': 'Accessory_Images_Table',
            },
        ),
        migrations.CreateModel(
            name='PartsImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('parts_image', models.ImageField(upload_to='VehicleParts')),
                ('parts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehicleApp.vehiclepartsmodel')),
            ],
        ),
    ]
