# Generated by Django 5.0.1 on 2024-03-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleApp', '0004_brandimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleaccessorymodel',
            name='vehicle_accessory_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicleaccessorymodel',
            name='vehicle_accessory_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepartsmodel',
            name='vehicle_part_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepartsmodel',
            name='vehicle_part_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
