# Generated by Django 5.0.1 on 2024-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleApp', '0006_alter_servicemodel_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_body_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_brand',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_budget',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_color',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_fuel_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_model',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_transmission',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_variant',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
